# Generated by Django 4.1.2 on 2022-10-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbanzoperms',
            name='id_guser',
        ),
        migrations.RemoveField(
            model_name='historicalgarbanzoperms',
            name='id_guser',
        ),
    ]
