# Generated by Django 4.1.2 on 2022-10-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_garbanzoperms_system_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guserperms',
            options={},
        ),
    ]
