# Generated by Django 4.1.2 on 2022-10-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_guserperms_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guserperms",
            options={},
        ),
    ]
