# Generated by Django 4.1.2 on 2022-10-15 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_guserperms_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbanzoAssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('system_create_at', models.DateTimeField(auto_now_add=True)),
                ('system_edited_at', models.DateTimeField(auto_now=True)),
                ('system_active', models.BooleanField(default=True)),
                ('desc_asset_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarbanzoLinkType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('system_create_at', models.DateTimeField(auto_now_add=True)),
                ('system_edited_at', models.DateTimeField(auto_now=True)),
                ('system_active', models.BooleanField(default=True)),
                ('desc_garbazno_link', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guserperms',
            name='system_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='guserperms',
            unique_together={('id_gperms', 'id_guser')},
        ),
        migrations.CreateModel(
            name='HistoricalGarbanzoLinkType',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('system_create_at', models.DateTimeField(blank=True, editable=False)),
                ('system_edited_at', models.DateTimeField(blank=True, editable=False)),
                ('system_active', models.BooleanField(default=True)),
                ('desc_garbazno_link', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical garbanzo link type',
                'verbose_name_plural': 'historical garbanzo link types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGarbanzoAssetType',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('system_create_at', models.DateTimeField(blank=True, editable=False)),
                ('system_edited_at', models.DateTimeField(blank=True, editable=False)),
                ('system_active', models.BooleanField(default=True)),
                ('desc_asset_type', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical garbanzo asset type',
                'verbose_name_plural': 'historical garbanzo asset types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGarbanzoAssetItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('system_create_at', models.DateTimeField(blank=True, editable=False)),
                ('system_edited_at', models.DateTimeField(blank=True, editable=False)),
                ('system_active', models.BooleanField(default=True)),
                ('name_item', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('tag_number', models.CharField(max_length=100)),
                ('internal_number', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type_asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.garbanzoassettype')),
            ],
            options={
                'verbose_name': 'historical garbanzo asset item',
                'verbose_name_plural': 'historical garbanzo asset items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='garbanzoassettype',
            name='accepted_links',
            field=models.ManyToManyField(to='users.garbanzolinktype'),
        ),
        migrations.CreateModel(
            name='GarbanzoAssetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('system_create_at', models.DateTimeField(auto_now_add=True)),
                ('system_edited_at', models.DateTimeField(auto_now=True)),
                ('system_active', models.BooleanField(default=True)),
                ('name_item', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('tag_number', models.CharField(max_length=100)),
                ('internal_number', models.CharField(max_length=100)),
                ('type_asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.garbanzoassettype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
